// Copies contract ABIs from the Foundry build into the frontend as typed TS modules.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
const out = new URL("../web/src/lib/abi/", import.meta.url);
mkdirSync(out, { recursive: true });
for (const name of ["InheritanceVault", "VaultFactory"]) {
  const art = JSON.parse(readFileSync(new URL(`../contracts/out/${name}.sol/${name}.json`, import.meta.url), "utf8"));
  writeFileSync(new URL(`${name}.ts`, out), `// generated by scripts/export-abi.ts — do not edit\nexport const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(art.abi, null, 2)} as const;\n`);
  console.log("wrote", name);
}
